#document settings
title: Federal Spending Transparency
desc: "The Federal Spending Transparency GitHub page is a collaboration space for stakeholders inside and outside government to stay informed on Digital Accountability and Transparency Act of 2014 (DATA Act) Implementation. The DATA Act makes federal spending data more accessible, searchable, and reliable. It makes it easier to understand how the federal government spends taxpayer dollars and serves as a tool for better oversight, data-centric decision-making, and innovation both inside and outside of government. The U.S. Department of the Treasury and the Office of Management and Budget are lead the government-wide implementation of the DATA Act.
Additionally, the page hosts the alpha version of the Data Lab at USAspending.gov, an initiative by the U.S. Department of the Treasury to create visualizations and analyses using federal spending data to help the public, researchers, government entities and others understand, and use the data from USAspending.gov."
url: //fedspendingtransparency.github.io/
repo_name: fedspendingtransparency.github.io
branch: master
encoding: utf-8



#global settings, no need to change these
root_url: //fedspendingtransparency.github.io
org_name: fedspendingtransparency

# default build settings for running locally, no need to edit
highlighter: rouge
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "LICENSE"]
markdown: kramdown
# markdown: redcarpet
# redcarpet:
#   extensions: []
relative_permalinks: false

gems:
 - jekyll-redirect-from

whitelist:
 - jekyll-redirect-from

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Data Model
   url: /data-model
 #- title: DAIMS v1.1
 #  url: /DAIMS-v1.1
 # - title: Data Broker
 #   url: /data-broker
 - title: User-Centered Design
   url: /user-centered-design
 - title: Get Involved
   url: "/get-involved"
 - title: DATA Act-ivity
   url: "/act-ivity" 
 - title: Data Lab
   url: "/data-lab"

 # - title: Discuss
 #   url: "https://github.com/fedspendingtransparency/fedspendingtransparency.github.io/issues"
 # - title: Get Updates
 #   url: "https://gsa.us9.list-manage.com/subscribe?u=6f1977de9eff4c384dc8d6527&id=5cee0e93aa"

sass:
  sass_dir:          assets/_scss
  #style:            :compressed
